ident:
  ga: G-404SVEYYL0

brand:
  name:
  - Still
  - Wild
  - Healing
  social:
  - title: instagram
    url: https://www.instagram.com/stillwildhealing/

nav:
- title: Forest Immersion
  url: '/#readme'
